FROM maven:3.5.2-jdk-8-alpine AS MAVEN_TOOL_CHAIN

COPY pom.xml /tmp/

COPY src /tmp/src/

WORKDIR /usr/src/app

RUN mvn package
 
FROM tomcat:9.0-jre8-alpine
COPY --from=MAVEN_TOOL_CHAIN /tmp/target/AyoWebAppTest*.jar $CATALINA_HOME/webapps/AyoWebAppTest.jar
 
HEALTHCHECK --interval=1m --timeout=3s CMD wget --quiet --tries=1 --spider http://localhost:8084/onlineconvertunits/ || exit 1